modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="zhengelss_aditions"
version="4.1.3"
displayName="Zhengels's aditions"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator."
authors="Zhengels"
description="Adds some vanila+ stuff. Also i suggest u mod \"polymorph\"."
displayTest="IGNORE_SERVER_VERSION"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.zhengelss_aditions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.zhengelss_aditions]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration