
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.zhengelssaditions.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.event.BuildCreativeModeTabContentsEvent;

import net.minecraft.world.item.Items;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.CreativeModeTabs;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.network.chat.Component;
import net.minecraft.core.registries.Registries;

import net.mcreator.zhengelssaditions.ZhengelssAditionsMod;

@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD)
public class ZhengelssAditionsModTabs {
	public static final DeferredRegister<CreativeModeTab> REGISTRY = DeferredRegister.create(Registries.CREATIVE_MODE_TAB, ZhengelssAditionsMod.MODID);
	public static final RegistryObject<CreativeModeTab> CREATIVE = REGISTRY.register("creative",
			() -> CreativeModeTab.builder().title(Component.translatable("item_group.zhengelss_aditions.creative")).icon(() -> new ItemStack(Items.FIREWORK_STAR)).displayItems((parameters, tabData) -> {
				tabData.accept(ZhengelssAditionsModItems.DIAMOND.get());
				tabData.accept(ZhengelssAditionsModBlocks.RANDOMORE.get().asItem());
				tabData.accept(ZhengelssAditionsModBlocks.STONEVARIATION.get().asItem());
				tabData.accept(ZhengelssAditionsModBlocks.OAKVARIATIONS.get().asItem());
				tabData.accept(ZhengelssAditionsModBlocks.SANDSTONEVARIATIONS.get().asItem());
				tabData.accept(ZhengelssAditionsModBlocks.RAWIRONBLOCK.get().asItem());
				tabData.accept(ZhengelssAditionsModBlocks.RAWGOLDBLOCK.get().asItem());
				tabData.accept(ZhengelssAditionsModBlocks.RAWCOPPERBLOCK.get().asItem());
				tabData.accept(ZhengelssAditionsModBlocks.BRICKSVARIATIONS.get().asItem());
				tabData.accept(ZhengelssAditionsModBlocks.BRICKSLABVARIATIONS_1.get().asItem());
				tabData.accept(ZhengelssAditionsModBlocks.BRICKSTAIRSVARIATIONS.get().asItem());
				tabData.accept(ZhengelssAditionsModBlocks.COBBLESTONEVARIATIONSBLOCK.get().asItem());
				tabData.accept(ZhengelssAditionsModItems.XPSTORAGE_1.get());
				tabData.accept(ZhengelssAditionsModItems.XPSTORAGE_2.get());
				tabData.accept(ZhengelssAditionsModItems.XPSTORAGE_3.get());
				tabData.accept(ZhengelssAditionsModItems.XPSTORAGE_4.get());
				tabData.accept(ZhengelssAditionsModItems.XPSTORAGE_5.get());
				tabData.accept(ZhengelssAditionsModItems.XPSTORAGE_6.get());
				tabData.accept(ZhengelssAditionsModItems.XPSTORAGE_7.get());
				tabData.accept(ZhengelssAditionsModItems.XPSTORAGE_8.get());
				tabData.accept(ZhengelssAditionsModItems.XPSTORAGE_9.get());
				tabData.accept(ZhengelssAditionsModItems.XPSTORAGE_10.get());
				tabData.accept(ZhengelssAditionsModItems.COPPERTOOLOXIDIZETEST.get());
				tabData.accept(ZhengelssAditionsModItems.ROTTENCOOKHATDISPLAYITEM.get());
				tabData.accept(ZhengelssAditionsModItems.COOKHATDISPLAYITEM.get());
			}).build());

	@SubscribeEvent
	public static void buildTabContentsVanilla(BuildCreativeModeTabContentsEvent tabData) {
		if (tabData.getTabKey() == CreativeModeTabs.COMBAT) {
			tabData.accept(ZhengelssAditionsModItems.COPPERARMOUR_HELMET.get());
			tabData.accept(ZhengelssAditionsModItems.COPPERARMOUR_CHESTPLATE.get());
			tabData.accept(ZhengelssAditionsModItems.COPPERARMOUR_LEGGINGS.get());
			tabData.accept(ZhengelssAditionsModItems.COPPERARMOUR_BOOTS.get());
			tabData.accept(ZhengelssAditionsModItems.COPPERSWORD.get());
			tabData.accept(ZhengelssAditionsModItems.DIORITESWORD.get());
			tabData.accept(ZhengelssAditionsModItems.GRANITESWORD.get());
			tabData.accept(ZhengelssAditionsModItems.ANDESITESWORD.get());
			tabData.accept(ZhengelssAditionsModItems.EXPOSEDCOPPERSWORD.get());
			tabData.accept(ZhengelssAditionsModItems.EXPOSEDCOPPERARMOUR_HELMET.get());
			tabData.accept(ZhengelssAditionsModItems.EXPOSEDCOPPERARMOUR_CHESTPLATE.get());
			tabData.accept(ZhengelssAditionsModItems.EXPOSEDCOPPERARMOUR_LEGGINGS.get());
			tabData.accept(ZhengelssAditionsModItems.EXPOSEDCOPPERARMOUR_BOOTS.get());
			tabData.accept(ZhengelssAditionsModItems.WEATHEREDCOPPERSWORD.get());
			tabData.accept(ZhengelssAditionsModItems.WEATHEREDCOPPERARMOUR_HELMET.get());
			tabData.accept(ZhengelssAditionsModItems.WEATHEREDCOPPERARMOUR_CHESTPLATE.get());
			tabData.accept(ZhengelssAditionsModItems.WEATHEREDCOPPERARMOUR_LEGGINGS.get());
			tabData.accept(ZhengelssAditionsModItems.WEATHEREDCOPPERARMOUR_BOOTS.get());
			tabData.accept(ZhengelssAditionsModItems.OXIDIZEDCOPPERSWORD.get());
			tabData.accept(ZhengelssAditionsModItems.OXIDIZEDCOPPERARMOUR_HELMET.get());
			tabData.accept(ZhengelssAditionsModItems.OXIDIZEDCOPPERARMOUR_CHESTPLATE.get());
			tabData.accept(ZhengelssAditionsModItems.OXIDIZEDCOPPERARMOUR_LEGGINGS.get());
			tabData.accept(ZhengelssAditionsModItems.OXIDIZEDCOPPERARMOUR_BOOTS.get());
			tabData.accept(ZhengelssAditionsModItems.AMETHYSTSWORD.get());
			tabData.accept(ZhengelssAditionsModItems.SANDSTONESWORD.get());
			tabData.accept(ZhengelssAditionsModItems.WAXEDWEATHEREDCOPPERARMOUR_HELMET.get());
			tabData.accept(ZhengelssAditionsModItems.WAXEDWEATHEREDCOPPERARMOUR_CHESTPLATE.get());
			tabData.accept(ZhengelssAditionsModItems.WAXEDWEATHEREDCOPPERARMOUR_LEGGINGS.get());
			tabData.accept(ZhengelssAditionsModItems.WAXEDWEATHEREDCOPPERARMOUR_BOOTS.get());
			tabData.accept(ZhengelssAditionsModItems.WAXEDWEATHEREDCOPPERSWORD.get());
			tabData.accept(ZhengelssAditionsModItems.WAXEDEXPOSEDCOPPERARMOUR_HELMET.get());
			tabData.accept(ZhengelssAditionsModItems.WAXEDEXPOSEDCOPPERARMOUR_CHESTPLATE.get());
			tabData.accept(ZhengelssAditionsModItems.WAXEDEXPOSEDCOPPERARMOUR_LEGGINGS.get());
			tabData.accept(ZhengelssAditionsModItems.WAXEDEXPOSEDCOPPERARMOUR_BOOTS.get());
			tabData.accept(ZhengelssAditionsModItems.WAXEDEXPOSEDCOPPERSWORD.get());
			tabData.accept(ZhengelssAditionsModItems.WAXEDCOPPERARMOUR_HELMET.get());
			tabData.accept(ZhengelssAditionsModItems.WAXEDCOPPERARMOUR_CHESTPLATE.get());
			tabData.accept(ZhengelssAditionsModItems.WAXEDCOPPERARMOUR_LEGGINGS.get());
			tabData.accept(ZhengelssAditionsModItems.WAXEDCOPPERARMOUR_BOOTS.get());
			tabData.accept(ZhengelssAditionsModItems.WAXEDCOPPERSWORD.get());
			tabData.accept(ZhengelssAditionsModItems.COBBLEDDEEPSLATESWORD.get());
			tabData.accept(ZhengelssAditionsModItems.LIGHTSWORD.get());
			tabData.accept(ZhengelssAditionsModItems.LIGHTSWORD_2.get());
			tabData.accept(ZhengelssAditionsModItems.LIGHTSWORD_3.get());
			tabData.accept(ZhengelssAditionsModItems.FIRESWORD.get());
			tabData.accept(ZhengelssAditionsModItems.FIRESWORD_2.get());
			tabData.accept(ZhengelssAditionsModItems.FIRESWORD_3.get());
			tabData.accept(ZhengelssAditionsModItems.EMERALDSWORD.get());
			tabData.accept(ZhengelssAditionsModItems.EMERALDSWORD_2.get());
			tabData.accept(ZhengelssAditionsModItems.EMERALDSWORD_3.get());
			tabData.accept(ZhengelssAditionsModItems.IRONKNUCKLES.get());
			tabData.accept(ZhengelssAditionsModItems.GOLDENKNUCKLES.get());
			tabData.accept(ZhengelssAditionsModItems.DIAMONDKNUCKLES.get());
			tabData.accept(ZhengelssAditionsModItems.NETHERITEKNUCKLES.get());
			tabData.accept(ZhengelssAditionsModItems.COPPERKNUCKLES.get());
			tabData.accept(ZhengelssAditionsModItems.EXPOSEDCOPPERKNUCKLES.get());
			tabData.accept(ZhengelssAditionsModItems.WEATHEREDCOPPERKNUCKLES.get());
			tabData.accept(ZhengelssAditionsModItems.OXIDIZEDCOPPERKNUCKLES.get());
			tabData.accept(ZhengelssAditionsModItems.WAXEDCOPPERKNUCKLES.get());
			tabData.accept(ZhengelssAditionsModItems.WAXEDEXPOSEDCOPPERKNUCKLES.get());
			tabData.accept(ZhengelssAditionsModItems.WAXEDWEATHEREDCOPPERKNUCKLES.get());
			tabData.accept(ZhengelssAditionsModItems.OBSIDIANSWORD.get());
		} else if (tabData.getTabKey() == CreativeModeTabs.INGREDIENTS) {
			tabData.accept(ZhengelssAditionsModItems.RUNESTONE.get());
			tabData.accept(ZhengelssAditionsModItems.TOOLTRIM.get());
			tabData.accept(ZhengelssAditionsModItems.EXPIRIENCEBIT.get());
			tabData.accept(ZhengelssAditionsModItems.EXPIRIENCEPIECE.get());
			tabData.accept(ZhengelssAditionsModItems.EXPIRIENCESHARD.get());
			tabData.accept(ZhengelssAditionsModItems.EXPIRIENCEROCK.get());
			tabData.accept(ZhengelssAditionsModItems.EXPIRIENCEBOULDER.get());
			tabData.accept(ZhengelssAditionsModItems.CRUCIBLE.get());
		} else if (tabData.getTabKey() == CreativeModeTabs.REDSTONE_BLOCKS) {
			tabData.accept(ZhengelssAditionsModBlocks.FIREBOMB.get().asItem());
			tabData.accept(ZhengelssAditionsModBlocks.SHRAPNELTNT.get().asItem());
		} else if (tabData.getTabKey() == CreativeModeTabs.TOOLS_AND_UTILITIES) {
			tabData.accept(ZhengelssAditionsModItems.WOODENSCYTHE.get());
			tabData.accept(ZhengelssAditionsModItems.WOODENHAMMER.get());
			tabData.accept(ZhengelssAditionsModItems.STONESCYTHE.get());
			tabData.accept(ZhengelssAditionsModItems.STONEHAMMER.get());
			tabData.accept(ZhengelssAditionsModItems.GOLDSKYTHE.get());
			tabData.accept(ZhengelssAditionsModItems.GOLDENHAMMER.get());
			tabData.accept(ZhengelssAditionsModItems.IRONSCYTHE.get());
			tabData.accept(ZhengelssAditionsModItems.IRONHAMMER.get());
			tabData.accept(ZhengelssAditionsModItems.DIAMONDSKYTHE.get());
			tabData.accept(ZhengelssAditionsModItems.DIAMONDHAMMER.get());
			tabData.accept(ZhengelssAditionsModItems.NETHERITESKYTHE.get());
			tabData.accept(ZhengelssAditionsModItems.NETHERITEHAMMER.get());
			tabData.accept(ZhengelssAditionsModItems.COPPERAXE.get());
			tabData.accept(ZhengelssAditionsModItems.COPPERPICKAXE.get());
			tabData.accept(ZhengelssAditionsModItems.COPPERSHOVEL.get());
			tabData.accept(ZhengelssAditionsModItems.COPPERHOE.get());
			tabData.accept(ZhengelssAditionsModItems.COPPERSCYTHE.get());
			tabData.accept(ZhengelssAditionsModItems.COPPERHAMMER.get());
			tabData.accept(ZhengelssAditionsModItems.DIORITEAXE.get());
			tabData.accept(ZhengelssAditionsModItems.DIORITEPICKAXE.get());
			tabData.accept(ZhengelssAditionsModItems.DIORITESHOVEL.get());
			tabData.accept(ZhengelssAditionsModItems.DIORITEHOE.get());
			tabData.accept(ZhengelssAditionsModItems.DIORITESCYTHE.get());
			tabData.accept(ZhengelssAditionsModItems.DIORITEHAMMER.get());
			tabData.accept(ZhengelssAditionsModItems.GRANITEAXE.get());
			tabData.accept(ZhengelssAditionsModItems.GRANITEPICKAXE.get());
			tabData.accept(ZhengelssAditionsModItems.GRANITESHOVEL.get());
			tabData.accept(ZhengelssAditionsModItems.GRANITEHOE.get());
			tabData.accept(ZhengelssAditionsModItems.GRANITESCYTHE.get());
			tabData.accept(ZhengelssAditionsModItems.GRANITEHAMMER.get());
			tabData.accept(ZhengelssAditionsModItems.ANDESITEAXE.get());
			tabData.accept(ZhengelssAditionsModItems.ANDESITEPICKAXE.get());
			tabData.accept(ZhengelssAditionsModItems.ANDESITESHOVEL.get());
			tabData.accept(ZhengelssAditionsModItems.ANDESITEHOE.get());
			tabData.accept(ZhengelssAditionsModItems.ANDESITESCYTHE.get());
			tabData.accept(ZhengelssAditionsModItems.ANDESITEHAMMER.get());
			tabData.accept(ZhengelssAditionsModItems.EXPOSEDCOPPERPICKAXE.get());
			tabData.accept(ZhengelssAditionsModItems.EXPOSEDCOPPERAXE.get());
			tabData.accept(ZhengelssAditionsModItems.EXPOSEDCOPPERSHOVEL.get());
			tabData.accept(ZhengelssAditionsModItems.EXPOSEDCOPPERHOE.get());
			tabData.accept(ZhengelssAditionsModItems.EXPOSEDCOPPERSKYTHE.get());
			tabData.accept(ZhengelssAditionsModItems.EXPOSEDCOPPERHAMMER.get());
			tabData.accept(ZhengelssAditionsModItems.WEATHEREDCOPPERPICKAXE.get());
			tabData.accept(ZhengelssAditionsModItems.WEATHEREDCOPPERAXE.get());
			tabData.accept(ZhengelssAditionsModItems.WEATHEREDCOPPERSHOVEL.get());
			tabData.accept(ZhengelssAditionsModItems.WEATHEREDCOPPERHOE.get());
			tabData.accept(ZhengelssAditionsModItems.WEATHEREDCOPPERSKYTHE.get());
			tabData.accept(ZhengelssAditionsModItems.WEATHEREDCOPPERHAMMER.get());
			tabData.accept(ZhengelssAditionsModItems.OXIDIZEDCOPPERPICKAXE.get());
			tabData.accept(ZhengelssAditionsModItems.OXIDIZEDCOPPERAXE.get());
			tabData.accept(ZhengelssAditionsModItems.OXIDIZEDCOPPERSHOVEL.get());
			tabData.accept(ZhengelssAditionsModItems.OXIDIZEDCOPPERHOE.get());
			tabData.accept(ZhengelssAditionsModItems.OXIDIZEDCOPPERSKYTHE.get());
			tabData.accept(ZhengelssAditionsModItems.OXIDIZEDCOPPERHAMMER.get());
			tabData.accept(ZhengelssAditionsModItems.AMETHYSTAXE.get());
			tabData.accept(ZhengelssAditionsModItems.AMETHYSTPICKAXE.get());
			tabData.accept(ZhengelssAditionsModItems.AMETHYSTSHOVEL.get());
			tabData.accept(ZhengelssAditionsModItems.AMETHYSTHOE.get());
			tabData.accept(ZhengelssAditionsModItems.AMETHYSTSCYTHE.get());
			tabData.accept(ZhengelssAditionsModItems.AMETHYSTHAMMER.get());
			tabData.accept(ZhengelssAditionsModItems.SANDSTONEAXE.get());
			tabData.accept(ZhengelssAditionsModItems.SANDSTONEPICKAXE.get());
			tabData.accept(ZhengelssAditionsModItems.SANDSTONESHOVEL.get());
			tabData.accept(ZhengelssAditionsModItems.SANDSTONEHOE.get());
			tabData.accept(ZhengelssAditionsModItems.WAXEDWEATHEREDCOPPERHOE.get());
			tabData.accept(ZhengelssAditionsModItems.WAXEDWEATHEREDCOPPERSHOVEL.get());
			tabData.accept(ZhengelssAditionsModItems.WAXEDWEATHEREDCOPPERAXE.get());
			tabData.accept(ZhengelssAditionsModItems.WAXEDWEATHEREDCOPPERPICKAXE.get());
			tabData.accept(ZhengelssAditionsModItems.WAXEDWEATHEREDCOPPERSKYTHE.get());
			tabData.accept(ZhengelssAditionsModItems.WAXEDWEATHEREDCOPPERHAMMER.get());
			tabData.accept(ZhengelssAditionsModItems.WAXEDEXPOSEDCOPPERHOE.get());
			tabData.accept(ZhengelssAditionsModItems.WAXEDEXPOSEDCOPPERSHOVEL.get());
			tabData.accept(ZhengelssAditionsModItems.WAXEDEXPOSEDCOPPERAXE.get());
			tabData.accept(ZhengelssAditionsModItems.WAXEDEXPOSEDCOPPERPICKAXE.get());
			tabData.accept(ZhengelssAditionsModItems.WAXEDEXPOSEDCOPPERSKYTHE.get());
			tabData.accept(ZhengelssAditionsModItems.WAXEDEXPOSEDCOPPERHAMMER.get());
			tabData.accept(ZhengelssAditionsModItems.WAXEDCOPPERAXE.get());
			tabData.accept(ZhengelssAditionsModItems.WAXEDCOPPERPICKAXE.get());
			tabData.accept(ZhengelssAditionsModItems.WAXEDCOPPERSHOVEL.get());
			tabData.accept(ZhengelssAditionsModItems.WAXEDCOPPERHOE.get());
			tabData.accept(ZhengelssAditionsModItems.WAXEDCOPPERSKYTHE.get());
			tabData.accept(ZhengelssAditionsModItems.WAXEDCOPPERHAMMER.get());
			tabData.accept(ZhengelssAditionsModItems.COBBLEDDEEPSLATEAXE.get());
			tabData.accept(ZhengelssAditionsModItems.COBBLEDDEEPSLATEPICKAXE.get());
			tabData.accept(ZhengelssAditionsModItems.COBBLEDDEEPSLATESHOVEL.get());
			tabData.accept(ZhengelssAditionsModItems.COBBLEDDEEPSLATEHOE.get());
			tabData.accept(ZhengelssAditionsModItems.COBBLEDDEEPSLATESKYTHE.get());
			tabData.accept(ZhengelssAditionsModItems.DEEPSLATEHAMMER.get());
			tabData.accept(ZhengelssAditionsModItems.SWEETWATER_BUCKET.get());
			tabData.accept(ZhengelssAditionsModItems.AMETHYSTTOTEM.get());
			tabData.accept(ZhengelssAditionsModItems.LAVAAXE.get());
			tabData.accept(ZhengelssAditionsModItems.LAVAPICKAXE.get());
			tabData.accept(ZhengelssAditionsModItems.LAVASWORD.get());
			tabData.accept(ZhengelssAditionsModItems.LAVASHOVEL.get());
			tabData.accept(ZhengelssAditionsModItems.LAVAHOE.get());
			tabData.accept(ZhengelssAditionsModItems.LAVASKYTHE.get());
			tabData.accept(ZhengelssAditionsModItems.LAVAHAMMER.get());
			tabData.accept(ZhengelssAditionsModItems.OBSIDIANAXE.get());
			tabData.accept(ZhengelssAditionsModItems.OBSIDIANPICKAXE.get());
			tabData.accept(ZhengelssAditionsModItems.OBSIDIANSHOVEL.get());
			tabData.accept(ZhengelssAditionsModItems.OBSIDIANHOE.get());
			tabData.accept(ZhengelssAditionsModItems.OBSIDIANSKYTHE.get());
			tabData.accept(ZhengelssAditionsModItems.OBSIDIANHAMMER.get());
			tabData.accept(ZhengelssAditionsModItems.OBSIDIANTOTEM.get());
		} else if (tabData.getTabKey() == CreativeModeTabs.BUILDING_BLOCKS) {
			tabData.accept(ZhengelssAditionsModBlocks.AMETHYSTLAMP.get().asItem());
			tabData.accept(ZhengelssAditionsModBlocks.EXPOSEDAMETHISTLAMP.get().asItem());
			tabData.accept(ZhengelssAditionsModBlocks.WEATHEREDAMETHISTLAMP.get().asItem());
			tabData.accept(ZhengelssAditionsModBlocks.OXIDIZEDAMETHISTLAMP.get().asItem());
			tabData.accept(ZhengelssAditionsModBlocks.WAXED_AMETHYSTLAMP.get().asItem());
			tabData.accept(ZhengelssAditionsModBlocks.WAXEDEXPOSED_AMETHYSTLAMP.get().asItem());
			tabData.accept(ZhengelssAditionsModBlocks.WAXEDWEATHEREDAMETHYSTLAMP.get().asItem());
			tabData.accept(ZhengelssAditionsModBlocks.COPPERLANTERN.get().asItem());
			tabData.accept(ZhengelssAditionsModBlocks.EXPOSEDCOPPERLANTERN.get().asItem());
			tabData.accept(ZhengelssAditionsModBlocks.WEATHEREDCOPPERLANTERN.get().asItem());
			tabData.accept(ZhengelssAditionsModBlocks.OXIDIZEDCOPPERLANTERN.get().asItem());
			tabData.accept(ZhengelssAditionsModBlocks.WAXEDCOPPERLANTERN.get().asItem());
			tabData.accept(ZhengelssAditionsModBlocks.WAXEDEXPOSEDCOPPERLANTERN.get().asItem());
			tabData.accept(ZhengelssAditionsModBlocks.WAXEDWEATHEREDCOPPERLANTERN.get().asItem());
			tabData.accept(ZhengelssAditionsModBlocks.CRYSTALLIZEDSUGAR.get().asItem());
			tabData.accept(ZhengelssAditionsModBlocks.CLEARCRISTALLIZEDSUGAR.get().asItem());
			tabData.accept(ZhengelssAditionsModBlocks.CHISELEDCRISTALLIZEDSUGAR.get().asItem());
			tabData.accept(ZhengelssAditionsModBlocks.POLISHEDOBSIDIAN.get().asItem());
			tabData.accept(ZhengelssAditionsModBlocks.OBSIDIANBRICKS.get().asItem());
		} else if (tabData.getTabKey() == CreativeModeTabs.FOOD_AND_DRINKS) {
			tabData.accept(ZhengelssAditionsModItems.CRISTALLIZEDSUGARITEM.get());
			tabData.accept(ZhengelssAditionsModItems.CARAMEL.get());
			tabData.accept(ZhengelssAditionsModItems.CANDYCANE.get());
			tabData.accept(ZhengelssAditionsModItems.CHOCOLATE.get());
			tabData.accept(ZhengelssAditionsModItems.CHOCOLATEAPPLE.get());
			tabData.accept(ZhengelssAditionsModItems.VERYSWEETBERRIES.get());
			tabData.accept(ZhengelssAditionsModItems.WHITECANDY.get());
			tabData.accept(ZhengelssAditionsModItems.WHITEMELONCANDY.get());
			tabData.accept(ZhengelssAditionsModItems.WHITESUGARCANDY.get());
			tabData.accept(ZhengelssAditionsModItems.WHITEAPPLECANDY.get());
			tabData.accept(ZhengelssAditionsModItems.WHITECARROTCANDY.get());
			tabData.accept(ZhengelssAditionsModItems.WHITEBERRYCANDY.get());
			tabData.accept(ZhengelssAditionsModItems.BEETROOTWITHSTEAKSOUP.get());
			tabData.accept(ZhengelssAditionsModItems.MELONJUICEWITHSEAGRASS.get());
			tabData.accept(ZhengelssAditionsModItems.CHOCOLATEBERRIES.get());
			tabData.accept(ZhengelssAditionsModItems.SALMONSUSHIROLLS.get());
			tabData.accept(ZhengelssAditionsModItems.CODSUSHIROLLS.get());
			tabData.accept(ZhengelssAditionsModItems.TROPICALSUSHIROLLS.get());
			tabData.accept(ZhengelssAditionsModBlocks.LASAGNA.get().asItem());
			tabData.accept(ZhengelssAditionsModItems.SWEETBERRYICETEA.get());
			tabData.accept(ZhengelssAditionsModItems.GLOWINGBERRYICETEA.get());
			tabData.accept(ZhengelssAditionsModItems.VEGETABLESOUP.get());
			tabData.accept(ZhengelssAditionsModItems.ROTTENSOUP.get());
			tabData.accept(ZhengelssAditionsModItems.POISONOUSGOULASH.get());
			tabData.accept(ZhengelssAditionsModItems.SEAPICKLESOUP.get());
			tabData.accept(ZhengelssAditionsModBlocks.APPLEPIE.get().asItem());
		} else if (tabData.getTabKey() == CreativeModeTabs.FUNCTIONAL_BLOCKS) {
			tabData.accept(ZhengelssAditionsModBlocks.AMETHYSTLAMP.get().asItem());
			tabData.accept(ZhengelssAditionsModBlocks.EXPOSEDAMETHISTLAMP.get().asItem());
			tabData.accept(ZhengelssAditionsModBlocks.WEATHEREDAMETHISTLAMP.get().asItem());
			tabData.accept(ZhengelssAditionsModBlocks.OXIDIZEDAMETHISTLAMP.get().asItem());
			tabData.accept(ZhengelssAditionsModBlocks.WAXED_AMETHYSTLAMP.get().asItem());
			tabData.accept(ZhengelssAditionsModBlocks.WAXEDEXPOSED_AMETHYSTLAMP.get().asItem());
			tabData.accept(ZhengelssAditionsModBlocks.WAXEDWEATHEREDAMETHYSTLAMP.get().asItem());
			tabData.accept(ZhengelssAditionsModBlocks.COPPERLANTERN.get().asItem());
			tabData.accept(ZhengelssAditionsModBlocks.EXPOSEDCOPPERLANTERN.get().asItem());
			tabData.accept(ZhengelssAditionsModBlocks.WEATHEREDCOPPERLANTERN.get().asItem());
			tabData.accept(ZhengelssAditionsModBlocks.OXIDIZEDCOPPERLANTERN.get().asItem());
			tabData.accept(ZhengelssAditionsModBlocks.WAXEDCOPPERLANTERN.get().asItem());
			tabData.accept(ZhengelssAditionsModBlocks.WAXEDEXPOSEDCOPPERLANTERN.get().asItem());
			tabData.accept(ZhengelssAditionsModBlocks.WAXEDWEATHEREDCOPPERLANTERN.get().asItem());
			tabData.accept(ZhengelssAditionsModBlocks.GUNPOWDERBLOCK.get().asItem());
			tabData.accept(ZhengelssAditionsModBlocks.WETGUNPOWDERBLOCK.get().asItem());
			tabData.accept(ZhengelssAditionsModBlocks.SUGARBLOCK.get().asItem());
			tabData.accept(ZhengelssAditionsModBlocks.METALURGISTTABLE.get().asItem());
			tabData.accept(ZhengelssAditionsModBlocks.HEALRUNE.get().asItem());
			tabData.accept(ZhengelssAditionsModBlocks.LIGHTINGRUNE.get().asItem());
			tabData.accept(ZhengelssAditionsModBlocks.FIRERUNE.get().asItem());
			tabData.accept(ZhengelssAditionsModBlocks.SLOWDOWNRUNE.get().asItem());
			tabData.accept(ZhengelssAditionsModBlocks.SPEEDRUNE.get().asItem());
			tabData.accept(ZhengelssAditionsModBlocks.OBSIDIANFURNACE.get().asItem());
			tabData.accept(ZhengelssAditionsModBlocks.FIREBOMB.get().asItem());
			tabData.accept(ZhengelssAditionsModBlocks.SHRAPNELTNT.get().asItem());
			tabData.accept(ZhengelssAditionsModBlocks.XPFIER.get().asItem());
			tabData.accept(ZhengelssAditionsModBlocks.FOUNDRY.get().asItem());
		}
	}
}
